# scalc - A simple calculator
# Copyright (C) 2009  Alexander Korsunsky
#
# For terms and conditions of redistribution and modification of this file
# please see the file LICENSE.txt.


## tool definitions ##
LEX := flex
YACC := bison


## Project parameters ##
PROJNAME := scalc

## file definitions ##


# sources generated by parser and lexer tools
GEN_SRCS = \
	lex.$(PROJNAME).cpp lex.$(PROJNAME).hpp \
	$(PROJNAME).tab.cpp $(PROJNAME).tab.hpp

# all object files and all source files
ALL_OBJS = $(patsubst %.cc,%.o,$(ALL_SRCS:.cpp=.o))
ALL_SRCS = main.cpp $(filter %.cpp %.cc,$(GEN_SRCS))

# name of the resulting executable
EXOUT := $(PROJNAME)


# All disabled warnings
WARN_DISABLED := -Wno-unused-function

# compile everything with maximum warning level and debugging symbols
CXXFLAGS += -Wall -ansi $(WARN_DISABLED) -g



all: $(EXOUT)

lex.$(PROJNAME).cpp lex.$(PROJNAME).hpp: $(PROJNAME).l
	$(LEX) $(LEXFLAGS) -o$(@:.hpp=.cpp)  --header-file=$(@:.cpp=.hpp) $<

lex.$(PROJNAME).o: lex.$(PROJNAME).cpp lex.$(PROJNAME).hpp $(PROJNAME).tab.hpp

$(PROJNAME).tab.cpp $(PROJNAME).tab.hpp: $(PROJNAME).y
	$(YACC) $(YACCFLAGS) -d -o $(PROJNAME).tab.cpp $^

$(PROJNAME).tab.o: $(PROJNAME).tab.cpp $(PROJNAME).tab.hpp lex.$(PROJNAME).hpp

main.o: main.cpp $(PROJNAME).tab.hpp

$(EXOUT): $(ALL_OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^



# clean out all compiled files
.PHONY: clean
clean:
	rm -f $(EXOUT) $(ALL_OBJS)

# clean out all generated files
.PHONY: distclean
distclean: clean
	rm -f $(GEN_SRCS)

