# scalc - A simple calculator
# Copyright (C) 2009  Alexander Korsunsky
#
# For terms and conditions of redistribution and modification of this file
# please see the file LICENSE.txt.


## tool definitions ##
LEX := flex
YACCPP := bisonc++


## Project parameters ##
PROJNAME := scalc

## file definitions ##


# sources generated by parser and lexer tools
GEN_SRCS = lex.$(PROJNAME).cpp

# all object files and all source files
ALL_OBJS = $(patsubst %.cpp,%.o,$(ALL_SRCS))
ALL_SRCS = main.cpp $(filter %.cpp,$(GEN_SRCS))

# name of the resulting executable
EXOUT := $(PROJNAME)


# All disabled warnings
WARN_DISABLED := -Wno-unused-function

# compile everything with maximum warning level and debugging symbols
CXXFLAGS += -Wall -pedantic -ansi $(WARN_DISABLED) -g


all: $(EXOUT)

lex.$(PROJNAME).cpp: $(PROJNAME).l
	$(LEX) $(LEXFLAGS) -o$@ $^

lex.$(PROJNAME).o: lex.$(PROJNAME).cpp

$(EXOUT): $(ALL_OBJS) lex.$(PROJNAME).o
	$(CXX) $(CXXFLAGS) -o $@ $^


# clean out all compiled files
.PHONY: clean
clean:
	rm -f $(EXOUT) $(ALL_OBJS)

# clean out all generated files
.PHONY: distclean
distclean: clean
	rm -f $(GEN_SRCS)

